# Generated by Django 6.0.2 on 2026-02-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('projects', '0002_project_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.customer'),
        ),
    ]
