# Generated by Django 6.0.3 on 2026-04-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='turnaround_time',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('RUSHED', 'Rushed')], default='STANDARD', max_length=20),
        ),
    ]
