# Generated by Django 6.0.3 on 2026-03-23 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '__first__'),
        ('projects', '0003_alter_project_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('business_context', models.TextField()),
                ('scientific_context', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to='customer_portal.customercontact')),
            ],
        ),
    ]
