# Generated by Django 6.0.1 on 2026-01-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(max_length=200, blank=True)),
                ('model', models.CharField(max_length=200, blank=True)),
                ('serial_number', models.CharField(max_length=100, blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='instruments_created',
                    to=settings.AUTH_USER_MODEL
                )),
                ('updated_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='instruments_updated',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
