# Generated by Django 6.0.1 on 2026-02-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("manage_roles", "Can manage user role assignments")]},
        ),
        migrations.CreateModel(
            name="RoleAssignmentAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_name", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[("assigned", "Assigned"), ("removed", "Removed")],
                        max_length=16,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Actor that changed the role assignment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignment_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose role assignment changed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignment_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-changed_at",),
            },
        ),
    ]
