# Generated by Django 6.0.1 on 2026-02-02

from django.db import migrations

ROLE_PERMISSIONS = {
    "Lab Tech": {
        ("samples", "view_sample"),
    },
    "Analyst": {
        ("samples", "view_sample"),
        ("samples", "change_sample"),
    },
    "QA Reviewer": {
        ("samples", "view_sample"),
        ("samples", "approve_sample"),
    },
    "Lab Manager": {
        ("samples", "view_sample"),
        ("samples", "add_sample"),
        ("samples", "change_sample"),
        ("samples", "delete_sample"),
        ("samples", "approve_sample"),
    },
    "Customer Contact": {
        ("samples", "view_sample"),
    },
    "System Admin": {
        ("accounts", "manage_roles"),
        ("samples", "view_sample"),
        ("samples", "add_sample"),
        ("samples", "change_sample"),
        ("samples", "delete_sample"),
        ("samples", "approve_sample"),
    },
}


def seed_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_types = {
        "accounts": ContentType.objects.get_or_create(app_label="accounts", model="user")[0],
        "samples": ContentType.objects.get_or_create(app_label="samples", model="sample")[0],
    }
    permission_names = {
        "add_sample": "Can add sample",
        "change_sample": "Can change sample",
        "delete_sample": "Can delete sample",
        "view_sample": "Can view sample",
        "approve_sample": "Can approve sample",
        "manage_roles": "Can manage user role assignments",
    }

    for role_name, permission_refs in ROLE_PERMISSIONS.items():
        group, _ = Group.objects.get_or_create(name=role_name)

        permission_ids = []
        for app_label, codename in permission_refs:
            ct = content_types[app_label]
            perm, _ = Permission.objects.get_or_create(
                content_type=ct,
                codename=codename,
                defaults={"name": permission_names[codename]},
            )
            permission_ids.append(perm.id)

        group.permissions.set(permission_ids)


def unseed_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=ROLE_PERMISSIONS.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_roleassignmentaudit_alter_user_options"),
        ("samples", "0003_alter_sample_options"),
    ]

    operations = [
        migrations.RunPython(seed_roles, reverse_code=unseed_roles),
    ]
