# Generated by Django 6.0.1 on 2026-02-02

from django.db import migrations

ROLE_PERMISSIONS = {
    "Lab Tech": {
        ("samples", "view_sample"),
    },
    "Analyst": {
        ("samples", "view_sample"),
        ("samples", "change_sample"),
    },
    "QA Reviewer": {
        ("samples", "view_sample"),
        ("samples", "approve_sample"),
    },
    "Lab Manager": {
        ("samples", "view_sample"),
        ("samples", "add_sample"),
        ("samples", "change_sample"),
        ("samples", "delete_sample"),
        ("samples", "approve_sample"),
    },
    "Customer Contact": {
        ("samples", "view_sample"),
    },
    "System Admin": {
        ("accounts", "manage_roles"),
        ("samples", "view_sample"),
        ("samples", "add_sample"),
        ("samples", "change_sample"),
        ("samples", "delete_sample"),
        ("samples", "approve_sample"),
    },
}


def sync_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_types = {
        "accounts": ContentType.objects.get_or_create(app_label="accounts", model="user")[0],
        "samples": ContentType.objects.get_or_create(app_label="samples", model="sample")[0],
    }

    for role_name, permission_refs in ROLE_PERMISSIONS.items():
        group, _ = Group.objects.get_or_create(name=role_name)
        permission_ids = []
        for app_label, codename in permission_refs:
            permission_ids.append(Permission.objects.get(content_type=content_types[app_label], codename=codename).id)
        group.permissions.set(permission_ids)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_seed_baseline_roles"),
    ]

    operations = [
        migrations.RunPython(sync_roles, reverse_code=migrations.RunPython.noop),
    ]
