services:
  db:
    image: postgres:16
    container_name: wulims_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: env(DB_NAME)
      POSTGRES_USER: env(DB_USER)
      POSTGRES_PASSWORD: env(WULIMS_DB_PASSWORD)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
