---
title: "CS426 - Software Engineering II"
format:
  revealjs:
    theme: [dark, custom.scss] # Base + course styling
    transition: slide
    highlight-style: monokai # Better code highlighting
    slide-number: true
    progress: true
    controls: true
    hash: true
    code-overflow: wrap
    pdf-separate-fragments: true
    pdf-max-pages-per-slide: 1
