# Generated by Django 6.0.3 on 2026-05-24 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_customeraddresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Customer Memberships',
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('business_context', models.TextField(help_text='Business context and objectives for this project')),
                ('scientific_context', models.TextField(help_text='Scientific background and methodology')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to='customers.customer')),
                ('requesting_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to='customers.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
