# Generated by Django 6.0.2 on 2026-02-18 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("person_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, choices=[("MR", "Mr"), ("MS", "Ms"), ("MRS", "Mrs"), ("DR", "Dr")], max_length=10)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("suffix", models.CharField(blank=True, max_length=50)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("role_id", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "customer_id",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="people", to="customers.customer"),
                ),
            ],
        ),
    ]
