# Generated by Django 6.0.2 on 2026-02-24 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonPhoneNumber",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=32)),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("cell", "Cell"),
                            ("personal", "Personal"),
                            ("fax", "Fax"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="customers.person",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="personphonenumber",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("person_id",),
                name="customers_one_primary_phone_per_person",
            ),
        ),
    ]
