# Generated by Django 6.0.2 on 2026-02-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="customers.person",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("person_id", "email"), name="uniq_person_email"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("person_id",),
                        name="uniq_primary_email_per_person",
                    ),
                ],
            },
        ),
    ]
