# Generated by Django 6.0.1 on 2026-02-05 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred.')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status change'), ('system', 'System action')], help_text='Type of action performed.', max_length=50)),
                ('object_type', models.CharField(help_text='Model name of the affected object (e.g. Experiment, Sample).', max_length=100)),
                ('object_id', models.UUIDField(help_text='Primary key of the affected object.')),
                ('diff', models.JSONField(blank=True, help_text='Field-level changes: {field: {from: x, to: y}}', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null means system action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_ee9c56_idx')],
            },
        ),
    ]
