# Generated by Django 6.0.2 on 2026-02-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditevent',
            old_name='meta',
            new_name='diff',
        ),
    ]
