# Generated by Django 6.0.1 on 2026-02-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Event', 'verbose_name_plural': 'Audit Events'},
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_object__8a757b_idx',
            old_name='audit_audit_object__0e78a5_idx',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_type',
            field=models.ForeignKey(help_text='Model type of the affected object.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
