# Generated by Django 6.0.2 on 2026-02-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_meta_auditevent_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditevent',
            name='diff',
        ),
    ]
