# Generated by Django 6.0.2 on 2026-02-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_auditevent_diff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditevent',
            old_name='after',
            new_name='changes',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='before',
        ),
    ]
