# Generated by Django 6.0.2 on 2026-02-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_rename_after_auditevent_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='object_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
