# Generated by Django 6.0.1 on 2026-01-29 23:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='sample',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_id',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='sample_uuid',
            new_name='sample_id',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
