# Generated by Django 6.0.1 on 2026-02-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_remove_sample_id_alter_sample_sample_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={"permissions": [("approve_sample", "Can approve sample")]},
        ),
    ]
