# Generated by Django 6.0.2 on 2026-02-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('samples', '0003_alter_sample_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='projects.project'),
        ),
    ]
