# Generated by Django 6.0.2 on 2026-02-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_sample_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
