# Generated by Django 6.0.2 on 2026-02-13 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_sample_sample_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('analysis_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SampleAnalysis',
            fields=[
                ('sample_analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_analyses', to='samples.analysistype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='samples.sample')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(fields=('sample', 'analysis_type'), name='uniq_sample_analysis_type')],
            },
        ),
    ]
