# Generated by Django 6.0.2 on 2026-02-13 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_customer_id'),
        ('samples', '0006_analysistype_sampleanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='filtration',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Needed', 'Not Needed'), ('Lab to do', 'Lab To Do')], default='Lab to do', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='preservation',
            field=models.CharField(choices=[('Lab to do', 'Lab To Do')], default='Lab to do', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(('filtration__in', ['Done', 'Not Needed', 'Lab to do'])), name='sample_filtration_valid'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(('preservation', 'Lab to do')), name='sample_preservation_valid'),
        ),
    ]
